### ISSUE TITLE
#telugu library in ocr_training_data.py

### ISSUE THREAD

**Issue by harinath141** [ChillarAnand/01#7]
hi
@ChillarAnand I tried to compile the file ocr_training_data.py
I got an exception at import telugu..
telugu library??
can you give me the link of the library??
also can you please give me your mobile number??

**Comment by ChillarAnand** [comment]
Clone it and https://github.com/rakeshvar/chamanti_ocr & run above script from this folder.

**Comment by harinath141** [comment]
@ChillarAnand 
i run the script but i got exception 
  File "/home/harinath/chamanti_ocr/telugu/fonts.py", line 90
    print("[X]{}".format(f), end='\t')
Invalid syntax
Sorry if im troubling you.basically im a c# developer im a newbie to python
if u can give you number i can whatsapp you

**Comment by ChillarAnand** [comment]
Try `python3 ocr_train_data.py`

**Comment by ChillarAnand** [comment]
I hope issue is resolved now.
